import type { Metadata } from "next";
import "./globals.css";

const APP_NAME = process.env.NEXT_PUBLIC_APP_NAME ?? "Evidentize";

export const metadata: Metadata = {
  metadataBase: new URL(
    process.env.NEXT_PUBLIC_BASE_URL ??
    (process.env.VERCEL_URL ? `https://${process.env.VERCEL_URL}` : 'https://app.evidentize.io')
  ),
  applicationName: APP_NAME,
  title: `${APP_NAME} | Practice into proof. Proof into portfolio.`,
  description: "Realistic workplace simulations, AI-evaluated, with a portfolio that proves what you can do.",
  openGraph: {
    title: `${APP_NAME} | Practice into proof. Proof into portfolio.`,
    description: "Realistic workplace simulations, AI-evaluated, with a portfolio that proves what you can do.",
    siteName: APP_NAME,
  },
  twitter: {
    card: "summary_large_image",
    title: `${APP_NAME} | Practice into proof. Proof into portfolio.`,
    description: "Realistic workplace simulations, AI-evaluated, with a portfolio that proves what you can do.",
  },
  // Tab icon and OG/Twitter share image are generated by app/icon.tsx and
  // app/opengraph-image.tsx (Next.js file-convention routes) — no manual
  // `icons`/`images` entries here. The old entries pointed at /favicon.svg
  // and /og-image.png, neither of which exist in public/.
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,600;9..144,700&display=swap" rel="stylesheet" />
      </head>
      <body className="min-h-full flex flex-col antialiased" suppressHydrationWarning>
        {children}
      </body>
    </html>
  );
}