/**
 * Partner token primitives — sign and verify JWTs that carry candidate
 * provisioning grants from partners (Career Bridge Foundation, Join Momentum,
 * future partners) into the Evidentize platform.
 *
 * A token is generated by Evidentize's partner API (POST /api/partners/tokens)
 * when a partner reports a candidate has paid for discipline access. The
 * candidate redeems the token at /redeem?token=... to provision their account
 * and entitlements.
 *
 * Security model:
 *  - HS256 (HMAC-SHA256) symmetric signing using PARTNER_TOKEN_SIGNING_SECRET
 *  - Issuer claim ("iss") = "evidentize-partner-api"
 *  - Audience claim ("aud") = "evidentize-redeem"
 *  - Expiry ("exp") enforced strictly — default 7 days per Spec 5.1 Decision 12
 *  - Custom claims: partner_id, candidate_email, candidate_name, disciplines, token_id
 *
 * Token_id is a UUID generated at sign time and stored in partner_tokens.token_hash
 * (hashed). When verify() returns the token_id, the redemption handler can look it
 * up in the partner_tokens table to check revocation status and mark it redeemed.
 *
 * This module does NOT touch the database. It is pure cryptography.
 */

import {
  SignJWT,
  jwtVerify,
  errors as joseErrors,
  type JWTPayload,
} from 'jose'
import { randomUUID, createHash } from 'node:crypto'

const ISSUER = 'evidentize-partner-api'
const AUDIENCE = 'evidentize-redeem'
const ALG = 'HS256'

function getSigningKey(): Uint8Array {
  const secret = process.env.PARTNER_TOKEN_SIGNING_SECRET
  if (!secret) {
    throw new Error(
      'PARTNER_TOKEN_SIGNING_SECRET is not set. Add it to .env.local (and Vercel env vars).'
    )
  }
  if (secret.length < 32) {
    throw new Error(
      'PARTNER_TOKEN_SIGNING_SECRET is too short (<32 chars). Use `openssl rand -base64 32` to generate.'
    )
  }
  return new TextEncoder().encode(secret)
}

export type PartnerTokenClaims = {
  partner_id: string
  candidate_email: string
  candidate_name: string | null
  disciplines: string[]
  token_id: string
}

export type PartnerTokenPayload = PartnerTokenClaims & JWTPayload

export type SignPartnerTokenInput = {
  partnerId: string
  candidateEmail: string
  candidateName?: string | null
  disciplines: string[]
  expiresInSeconds?: number
}

const DEFAULT_TTL_SECONDS = 7 * 24 * 60 * 60 // 7 days

/**
 * Sign a partner token. Returns the JWT string plus the token_id (UUID) and
 * expires_at (Date). The caller is responsible for storing a hash of the token
 * (via hashPartnerToken) in the partner_tokens table for revocation lookup.
 */
export async function signPartnerToken(input: SignPartnerTokenInput): Promise<{
  token: string
  token_id: string
  expires_at: Date
}> {
  const tokenId = randomUUID()
  const ttl = input.expiresInSeconds ?? DEFAULT_TTL_SECONDS
  const issuedAt = Math.floor(Date.now() / 1000)
  const expiresAt = issuedAt + ttl

  if (!input.partnerId) throw new Error('partnerId is required')
  if (!input.candidateEmail) throw new Error('candidateEmail is required')
  if (!input.disciplines?.length) throw new Error('disciplines must be a non-empty array')

  const claims: PartnerTokenClaims = {
    partner_id: input.partnerId,
    candidate_email: input.candidateEmail.toLowerCase().trim(),
    candidate_name: input.candidateName?.trim() || null,
    disciplines: input.disciplines,
    token_id: tokenId,
  }

  const token = await new SignJWT({ ...claims })
    .setProtectedHeader({ alg: ALG })
    .setIssuer(ISSUER)
    .setAudience(AUDIENCE)
    .setIssuedAt(issuedAt)
    .setExpirationTime(expiresAt)
    .setSubject(claims.candidate_email)
    .sign(getSigningKey())

  return {
    token,
    token_id: tokenId,
    expires_at: new Date(expiresAt * 1000),
  }
}

/**
 * Verify a partner token. Throws if the signature is invalid, the token is
 * expired, the issuer/audience don't match, or required claims are missing.
 *
 * The thrown error has a `code` property to distinguish failure modes:
 *  - 'INVALID_SIGNATURE'  — signature didn't verify
 *  - 'EXPIRED'            — token expired
 *  - 'INVALID_AUDIENCE'   — token was for a different audience
 *  - 'INVALID_ISSUER'     — token wasn't issued by us
 *  - 'MALFORMED'          — token didn't decode, or missing claims
 */
export class PartnerTokenVerificationError extends Error {
  constructor(
    public code:
      | 'INVALID_SIGNATURE'
      | 'EXPIRED'
      | 'INVALID_AUDIENCE'
      | 'INVALID_ISSUER'
      | 'MALFORMED',
    message: string
  ) {
    super(message)
    this.name = 'PartnerTokenVerificationError'
  }
}

export async function verifyPartnerToken(token: string): Promise<PartnerTokenPayload> {
  if (!token) throw new PartnerTokenVerificationError('MALFORMED', 'No token provided')

  try {
    const { payload } = await jwtVerify(token, getSigningKey(), {
      issuer: ISSUER,
      audience: AUDIENCE,
      algorithms: [ALG],
    })

    const claims = payload as PartnerTokenPayload
    if (
      !claims.partner_id ||
      !claims.candidate_email ||
      !Array.isArray(claims.disciplines) ||
      claims.disciplines.length === 0 ||
      !claims.token_id
    ) {
      throw new PartnerTokenVerificationError('MALFORMED', 'Required claims missing')
    }

    return claims
  } catch (err: unknown) {
    if (err instanceof PartnerTokenVerificationError) throw err

    // jose v6 throws typed errors. Map to our error codes by instanceof
    // checks rather than message-string matching, so the mapping is robust
    // to library-message changes and localisation.

    if (err instanceof joseErrors.JWTExpired) {
      throw new PartnerTokenVerificationError('EXPIRED', err.message)
    }

    if (err instanceof joseErrors.JWSSignatureVerificationFailed) {
      throw new PartnerTokenVerificationError('INVALID_SIGNATURE', err.message)
    }

    if (err instanceof joseErrors.JWTClaimValidationFailed) {
      // err.claim tells us which claim failed (e.g. "aud", "iss")
      const claim = (err as { claim?: string }).claim
      if (claim === 'aud') {
        throw new PartnerTokenVerificationError('INVALID_AUDIENCE', err.message)
      }
      if (claim === 'iss') {
        throw new PartnerTokenVerificationError('INVALID_ISSUER', err.message)
      }
      throw new PartnerTokenVerificationError('MALFORMED', err.message)
    }

    if (
      err instanceof joseErrors.JWTInvalid ||
      err instanceof joseErrors.JWSInvalid ||
      err instanceof joseErrors.JOSEError
    ) {
      throw new PartnerTokenVerificationError('MALFORMED', err.message)
    }

    // Unknown error class — re-wrap as MALFORMED with original message preserved.
    const msg = err instanceof Error ? err.message : String(err)
    throw new PartnerTokenVerificationError('MALFORMED', msg)
  }
}

/**
 * Hash a token for storage in partner_tokens.token_hash. Uses SHA-256.
 * We never store raw tokens — only hashes — so that a leaked database row
 * cannot be used to redeem a candidate's grant.
 */
export function hashPartnerToken(token: string): string {
  return createHash('sha256').update(token).digest('hex')
}
